spring:
  datasource:
    hikari:
      maximum-pool-size: 5
    driver-class-name: org.postgresql.Driver
    url: jdbc:${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false
  main:
    allow-bean-definition-overriding: true
server:
  port: ${PORT}

app:
    jwtSecret: projectSecretKey
    jwtExpirationMs: 86400000


